# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Readings', folder: 'pages', file: 'readings.html'}
- {name: 'Study', folder: 'pages', file: 'study.html'}
- {name: 'Random', folder: 'pages', file: 'random.html'}
- {name: 'Publications', folder: 'pages', file: 'publications.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/mengjie_zhao'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'envelope', link: 'mailto:mengjie@fastmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Contents Licensed CC BY NC SA 4.0'

# related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
